
const mockUser = {
  login: "Jesperwernborg",
  id: 58472246,
  node_id: "MDQ6VXNlcjU4NDcyMjQ2",
  avatar_url: "https://avatars.githubusercontent.com/u/58472246?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Jesperwernborg",
  html_url: "https://github.com/Jesperwernborg",
  followers_url: "https://api.github.com/users/Jesperwernborg/followers",
  following_url: "https://api.github.com/users/Jesperwernborg/following{/other_user}",
  gists_url: "https://api.github.com/users/Jesperwernborg/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Jesperwernborg/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Jesperwernborg/subscriptions",
  organizations_url: "https://api.github.com/users/Jesperwernborg/orgs",
  repos_url: "https://api.github.com/users/Jesperwernborg/repos",
  events_url: "https://api.github.com/users/Jesperwernborg/events{/privacy}",
  received_events_url: "https://api.github.com/users/Jesperwernborg/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 11,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2019-12-03T12:35:54Z",
  updated_at: "2021-04-27T12:00:50Z"
}
export default mockUser;